### ISSUE TITLE
Question about maintainence

### ISSUE THREAD

**Issue by Eein** [knutwalker/sea-of-stars-autosplitter#1]
Are you planning on continuing this autosplitter for the main game? 

I started toying with one here https://github.com/Eein/sea-of-stars-autosplitter

But havent had time to go further yet. 

If you are planning on supporting this further i can link mine here and archive mine - and help contribute here if time permits. 

Glad you got the il2cpp Class macro working - i did not have any luck :p

**Comment by knutwalker** [comment]
Hey, thanks for the ping. I want to continue with the autosplitter, especially when we actually have some rules and a leaderboard and we can figure out where runners want to split. The current split-at-every-boss is more like a starting point to get something started and I'll be happy to accept your contributions.
The Class macro thing was quite nice, I had a bunch of pointer paths before that. I guess the tricky part is that we can't use the regular wait methods on the TitleSequenceManager, since the instance disappears after character select.

**Comment by Eein** [comment]
Excellent! Ill archive mine - feel free to ask about any locations in memory because we are also working on an AI tas and ive done alot of work digging already. Thanks!
